Repository modern-agile-team/dev-portfolio, pull requests merged in 2022-07, with the labels that each got.

#23 Update contact component
  app/src/index.css
  app/src/lib/common/types/contact.ts
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Contact/ContactForm.tsx
Labels: enhancement

#29 Chore update techstacks component
  app/src/App.tsx
  app/src/lib/components/TechStack/TechStacks/ProgressBar.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackName.tsx
Labels: Chore

#31 [Update] add display block in img tag (#27)
  .gitignore
  app/.npmignore
  app/package-lock.json
  app/package.json
  app/public/index.html
  app/public/manifest.json
  app/src/App.tsx
  app/src/index.tsx
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/Channels/Channels.tsx
  app/src/lib/components/Header/Logo.tsx
  app/src/lib/components/Header/SideContainer/SideBarIcon.tsx
  app/src/lib/components/Intro/IntroTitle.tsx
  app/src/lib/components/Masonry/Image.tsx
  app/src/lib/components/TechStack/TechStackInput.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackName.tsx
  app/src/lib/dependencies/@iconify/react/api-extractor.iconify.json
  app/src/lib/dependencies/@iconify/react/api-extractor.offline.json
  app/src/lib/dependencies/@iconify/react/cleanup.js
  app/src/lib/dependencies/@iconify/react/dist/iconify.d.ts
  app/src/lib/dependencies/@iconify/react/dist/iconify.js
  app/src/lib/dependencies/@iconify/react/dist/iconify.mjs
  app/src/lib/dependencies/@iconify/react/dist/offline.d.ts
  app/src/lib/dependencies/@iconify/react/dist/offline.js
  app/src/lib/dependencies/@iconify/react/dist/offline.mjs
  app/src/lib/dependencies/@iconify/react/license.txt
  app/src/lib/dependencies/@iconify/react/offline/package.json
  app/src/lib/dependencies/@iconify/react/offline/readme.md
  app/src/lib/dependencies/@iconify/react/package.json
  app/src/lib/dependencies/@iconify/react/readme.md
  app/src/lib/dependencies/react-icons/fa/index.d.ts
  app/src/lib/dependencies/react-icons/fa/index.esm.js
  app/src/lib/dependencies/react-icons/fa/index.js
  app/src/lib/dependencies/react-icons/fa/package.json
  app/src/lib/dependencies/react-icons/lib/cjs/iconBase.d.ts
  app/src/lib/dependencies/react-icons/lib/cjs/iconBase.js
  app/src/lib/dependencies/react-icons/lib/cjs/iconContext.d.ts
  app/src/lib/dependencies/react-icons/lib/cjs/iconContext.js
  app/src/lib/dependencies/react-icons/lib/cjs/iconsManifest.d.ts
  app/src/lib/dependencies/react-icons/lib/cjs/iconsManifest.js
  app/src/lib/dependencies/react-icons/lib/cjs/index.d.ts
  app/src/lib/dependencies/react-icons/lib/cjs/index.js
  app/src/lib/dependencies/react-icons/lib/esm/iconBase.d.ts
  app/src/lib/dependencies/react-icons/lib/esm/iconBase.js
  app/src/lib/dependencies/react-icons/lib/esm/iconContext.d.ts
  app/src/lib/dependencies/react-icons/lib/esm/iconContext.js
  app/src/lib/dependencies/react-icons/lib/esm/iconsManifest.d.ts
  app/src/lib/dependencies/react-icons/lib/esm/iconsManifest.js
  app/src/lib/dependencies/react-icons/lib/esm/index.d.ts
  app/src/lib/dependencies/react-icons/lib/esm/index.js
  app/src/lib/dependencies/react-icons/lib/package.json
  app/tsconfig.json
Labels: Chore

#33 [Refactor]: change props name 'moveURL' into 'redirectURL' (#25)
  app/src/lib/components/Gallery/Item.tsx
Labels: Refactor

#39 [Feat] create vertical component that one of theme of experience (#36)
  app/src/App.tsx
  app/src/lib/components/Experience/Experience.tsx
  app/src/lib/components/Experience/History/Vertical.tsx
  app/src/lib/components/Experience/History/index.tsx
Labels: enhancement

#42 [Feat]: create useInteractiveMouseMove custom hook #36
  app/src/lib/common/hooks/useInteractiveMouseMove.tsx
Labels: enhancement

#41 [Chore] change masonry/image components to responsive web (#28)
  app/src/lib/components/Masonry/Image.tsx
  app/src/lib/components/Masonry/Masonry.tsx
Labels: enhancement

#44 [Chore] change header component to responsive web (#28)
  app/src/App.tsx
  app/src/lib/components/Experience/Experience.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Header/Logo.tsx
Labels: Chore

#47 [Refactor] Change wrong names 'uri' to 'url' #45
  app/src/lib/components/Channels/Channels.tsx
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Header/Logo.tsx
Labels: Refactor

#56 [Chore] add object-fit in item component (#54)
  app/src/lib/components/Gallery/Item.tsx
Labels: Chore

#58 [Update] add props in Image component (#50)
  app/src/lib/components/Masonry/Image.tsx
Labels: Chore

#59 [Refactor] modify Intro props in more detail (#49)
  app/src/lib/components/Intro/Intro.tsx
Labels: Refactor

#63 [Feat] reinforce carousel (#48)
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/Carousel/hooks.tsx
Labels: enhancement
