Repository modern-agile-team/dev-portfolio, pull requests merged in 2022-08, with the labels that each got.

#70 [Refactor] remove HardCode andd change already made Types #61
  app/src/lib/components/TechStack/TechStacks/ProgressBar.tsx
  app/src/lib/components/TechStack/TechStacks/TechStack.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackName.tsx
Labels: bug, Refactor

#65 [Update] add zoomWhenHover props to select hover event (#46)
  app/src/lib/components/Masonry/Image.tsx
Labels: enhancement

#67 [feature/pwr/#55] logoImg 프롭스가 없어도 동작되도록 수정
  app/package.json
  app/public/logo_test.png
  app/src/App.tsx
  app/src/lib/components/Channels/Channels.tsx
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Header/Logo.tsx
Labels: Chore

#69 [Update] set column count values based on number of child elements (#62)
  app/src/lib/components/Masonry/Masonry.tsx
Labels: enhancement

#71 [Refactor] remove props called 'styles' and must append those props in origin props #66
  app/src/App.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Header/Logo.tsx
  app/src/lib/components/Header/SideContainer/SideBar.tsx
  app/src/lib/components/Header/SideContainer/SideBarIcon.tsx
  app/src/lib/components/Header/SideContainer/SideContainer.tsx
Labels: Refactor, Chore

#72 Implementation of the function of collecting id registered in each prop and registering it in the sidebar #64
  app/src/App.tsx
  app/src/lib/common/types/contact.ts
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/Channels/Channels.tsx
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Experience/Experience.tsx
  app/src/lib/components/Gallery/Gallery.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Header/SideContainer/SideContainer.tsx
  app/src/lib/components/Intro/Intro.tsx
  app/src/lib/components/Masonry/Masonry.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackList.tsx
Labels: Refactor, enhancement, Chore

#79 [Build] update version to v0.3.4
  app/package.json
Labels: Chore

#84 [feature/pwr/#80]
  app/package.json
  app/src/App.tsx
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Header/SideContainer/SideContainer.tsx
Labels: bug, enhancement, Chore

#83 [Fix] fix carousel autoplay bug (#48)
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/Carousel/hooks.tsx
Labels: enhancement

#85 Feature/pwr/#77
  app/package.json
  app/src/App.tsx
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/TechStack/TechStacks/TechStack.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackList.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackName.tsx
Labels: bug, enhancement, Chore

#86 [Feat] enable custom player icon location (#48)
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/Carousel/hooks.tsx
  app/src/lib/components/Carousel/style.tsx
Labels: enhancement

#87 [Feat] add props isTextRising and textRisingSpeed that uprise text when it overflow wrapper (#53)
  app/src/lib/components/Gallery/Item.tsx
Labels: enhancement

#93 Feature/pwr/#82
  app/src/App.tsx
  app/src/lib/common/types/ComponentTypes/ContactType.ts
  app/src/lib/common/types/contact.ts
  app/src/lib/common/types/intro.ts
  app/src/lib/common/types/themes.ts
  app/src/lib/components/Contact/AboutMe.tsx
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Contact/ContactForm.tsx
  app/src/lib/components/Experience/Experience.tsx
  app/src/lib/components/Experience/History/Box.tsx
  app/src/lib/components/Header/SideContainer/SideBar.tsx
  app/src/lib/components/Header/SideContainer/SideBarItems.tsx
  app/src/lib/components/Intro/IntroForm.tsx
Labels: Refactor, Chore

#94 [feature/pwr/#89] move all of types to Type.ts
  app/src/App.tsx
  app/src/lib/common/types/ComponentTypes/CardType.ts
  app/src/lib/common/types/ComponentTypes/CarouselType.ts
  app/src/lib/common/types/ComponentTypes/ChannelType.ts
  app/src/lib/common/types/ComponentTypes/Contact/AboutMeInfoType.ts
  app/src/lib/common/types/ComponentTypes/Contact/ContactType.ts
  app/src/lib/common/types/ComponentTypes/ContactType.ts
  app/src/lib/common/types/ComponentTypes/ExperienceType.ts
  app/src/lib/common/types/ComponentTypes/GalleryType.ts
  app/src/lib/common/types/ComponentTypes/Header/HeaderLogoType.ts
  app/src/lib/common/types/ComponentTypes/Header/HeaderType.ts
  app/src/lib/common/types/ComponentTypes/Header/SideBar/SideBarIconType.ts
  app/src/lib/common/types/ComponentTypes/Header/SideBar/SideBarItemsType.ts
  app/src/lib/common/types/ComponentTypes/Header/SideBar/SideBarType.ts
  app/src/lib/common/types/ComponentTypes/Header/SideContainerType.ts
  app/src/lib/common/types/ComponentTypes/ImageType.ts
  app/src/lib/common/types/ComponentTypes/IntroType.ts
  app/src/lib/common/types/ComponentTypes/ItemType.ts
  app/src/lib/common/types/ComponentTypes/MasonryType.ts
  app/src/lib/common/types/ComponentTypes/TechStack/ProgressBarType.ts
  app/src/lib/common/types/ComponentTypes/TechStack/TechStackInputType.ts
  app/src/lib/common/types/ComponentTypes/TechStack/TechStackListType.ts
  app/src/lib/common/types/ComponentTypes/TechStack/TechStackNameType.ts
  app/src/lib/common/types/ComponentTypes/TechStack/TechStackType.ts
  app/src/lib/common/types/intro.ts
  app/src/lib/components/Card/Card.tsx
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/Carousel/hooks.tsx
  app/src/lib/components/Carousel/style.tsx
  app/src/lib/components/Channels/Channels.tsx
  app/src/lib/components/Contact/AboutMe.tsx
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Contact/ContactForm.tsx
  app/src/lib/components/Experience/Experience.tsx
  app/src/lib/components/Experience/History/Basic.tsx
  app/src/lib/components/Experience/History/Box.tsx
  app/src/lib/components/Experience/History/Vertical.tsx
  app/src/lib/components/Experience/History/index.tsx
  app/src/lib/components/Gallery/Gallery.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Header/HeaderLogo.tsx
  app/src/lib/components/Header/SideContainer.tsx
  app/src/lib/components/Header/SideContainer/SideBar.tsx
  app/src/lib/components/Header/SideContainer/SideBarIcon.tsx
  app/src/lib/components/Header/SideContainer/SideBarItems.tsx
  app/src/lib/components/Image/Image.tsx
  app/src/lib/components/Intro/Intro.tsx
  app/src/lib/components/Intro/IntroForm.tsx
  app/src/lib/components/Intro/IntroTitle.tsx
  app/src/lib/components/Item/Item.tsx
  app/src/lib/components/Masonry/Masonry.tsx
  app/src/lib/components/TechStack/TechStackInput.tsx
  app/src/lib/components/TechStack/TechStacks/ProgressBar.tsx
  app/src/lib/components/TechStack/TechStacks/TechStack.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackList.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackName.tsx
  app/src/lib/index.ts
Labels: Refactor

#95 [feature/pwr/#92]
  app/src/lib/common/types/ComponentTypes/Header/HeaderLogoType.ts
  app/src/lib/common/types/ComponentTypes/Header/HeaderType.ts
  app/src/lib/common/types/ComponentTypes/Header/SideBar/SideBarIconType.ts
  app/src/lib/common/types/ComponentTypes/Header/SideBar/SideBarType.ts
  app/src/lib/components/Channels/Channels.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Header/HeaderLogo.tsx
  app/src/lib/components/Header/SideContainer.tsx
  app/src/lib/components/Header/SideContainer/SideBarIcon.tsx
Labels: bug, Refactor, Chore

#98 [Feat] Carousel autoplay control button overflow (#97)
  app/package-lock.json
  app/package.json
  app/src/lib/components/Carousel/Carousel.tsx
  app/src/lib/components/Carousel/style.tsx
Labels: enhancement

#100 [Feat] reinforce Gallery Component (#81)
  app/src/lib/common/types/ComponentTypes/GalleryType.ts
  app/src/lib/components/Gallery/Gallery.tsx
Labels: enhancement

#103 [Refactor] update props type and add for simple code of Carousel #89
  app/src/lib/common/types/ComponentTypes/CarouselType.ts
  app/src/lib/components/Carousel/style.tsx
Labels: Refactor

#104 [Feat] add props in ProgressBar components
  app/package.json
  app/src/lib/common/types/ComponentTypes/TechStack/ProgressBarType.ts
  app/src/lib/components/TechStack/TechStacks/ProgressBar.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackList.tsx
Labels: enhancement
