Repository modern-agile-team/dev-portfolio, pull requests merged in 2022-10, with the labels that each got.

#154 [Feat] add components such as 'Skill' and 'Channel' etc. (#153)
  src/App.tsx
  src/lib/common/types/ComponentTypes/ChannelType.ts
  src/lib/common/types/ComponentTypes/Header/SideBar/SideBarType.ts
  src/lib/common/types/ComponentTypes/Header/SideContainerType.ts
  src/lib/common/types/ComponentTypes/SkillType.ts
  src/lib/components/Channels/Channel.tsx
  src/lib/components/Channels/Channels.tsx
  src/lib/components/Header/Header.tsx
  src/lib/components/Header/SideContainer.tsx
  src/lib/components/Skill/Skill.tsx
  src/lib/index.ts
Labels: enhancement

#157 [Feat] Scroll detected header (#156)
  src/lib/components/Header/Header.tsx
  src/lib/components/Header/SideContainer.tsx
  src/lib/components/Header/SideContainer/SideBar.tsx
Labels: enhancement

#159 [Docs] modify README.md to match modified props (#152)
  README.md
Labels: question

#160 [Deploy] update version to v2.0.0-beta-0.1
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/lib/components/Header/SideContainer.tsx
Labels: deploy

#162 [Refactor] Update Header component
  README.md
  src/App.tsx
  src/lib/common/types/ComponentTypes/ChannelType.ts
  src/lib/common/types/ComponentTypes/Header/HeaderLogoType.ts
  src/lib/common/types/ComponentTypes/Header/HeaderType.ts
  src/lib/components/Header/Header.tsx
  src/lib/components/Header/HeaderLogo.tsx
  src/lib/components/Header/SideContainer.tsx
  src/lib/components/Header/SideContainer/SideBar.tsx
  src/lib/components/Header/SideContainer/SideBarIcon.tsx
  src/lib/components/Header/SideContainer/SideBarItems.tsx
Labels: Refactor, Chore

#167 [Build] add CICD files and features
  .github/workflows/ci.yml
  .github/workflows/release-to-npm.yml
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  .releaserc
  README.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: build

#168 fix(ci.yml): remove lint attr of needs in lint
  .github/workflows/ci.yml
  .github/workflows/release-to-npm.yml
Labels: build

#169 [Build] add CICD files and features
  .github/workflows/ci.yml
  .github/workflows/release-to-npm.yml
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  .releaserc
  README.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: build

#170 build: update version to v2.0.0 #166
  package-lock.json
  package.json
Labels: build

#171 [Fix] fix carousel bug (#164)
  src/lib/components/Carousel/hooks.tsx
  src/lib/components/Item/Item.tsx
Labels: bug

#173 [Feat] add props of Intro, Contact, Skill, Item, Image
  src/App.css
  src/lib/common/types/ComponentTypes/ChannelType.ts
  src/lib/common/types/ComponentTypes/Contact/AboutMeInfoType.ts
  src/lib/common/types/ComponentTypes/Contact/ContactType.ts
  src/lib/common/types/ComponentTypes/Header/HeaderType.ts
  src/lib/common/types/ComponentTypes/ImageType.ts
  src/lib/common/types/ComponentTypes/IntroType.ts
  src/lib/common/types/ComponentTypes/ItemType.ts
  src/lib/common/types/ComponentTypes/SkillType.ts
  src/lib/components/Channels/Channels.tsx
  src/lib/components/Contact/AboutMe.tsx
  src/lib/components/Contact/Contact.tsx
  src/lib/components/Contact/ContactForm.tsx
  src/lib/components/Gallery/Gallery.tsx
  src/lib/components/Image/Image.tsx
  src/lib/components/Intro/Intro.tsx
  src/lib/components/Intro/IntroForm.tsx
  src/lib/components/Intro/IntroTitle.tsx
  src/lib/components/Item/Item.tsx
  src/lib/components/Skill/Skill.tsx
Labels: enhancement

#175 style(app.tsx): update UI only for testing
  src/App.tsx
Labels: Chore

#165 [Chore] add typedoc about Progressbar component (#153)
  src/lib/common/types/ComponentTypes/TechStack/ProgressBarType.ts
  src/lib/components/ProgressBar/ProgressBar.tsx
Labels: enhancement, good first issue

#174 docs: add ProgressBar description to README and make code beautiful (#152)
  README.md
Labels: Chore

#176 [Feat] add props in Exprience, VisitorComment, VisitorCounter component (#164)
  src/App.tsx
  src/lib/common/types/ComponentTypes/ExperienceType.ts
  src/lib/common/types/ComponentTypes/VisitorCommentType.ts
  src/lib/common/types/ComponentTypes/VisitorCounterType.ts
  src/lib/components/Experience/Experience.tsx
  src/lib/components/Experience/History/Basic.tsx
  src/lib/components/Experience/History/Box.tsx
  src/lib/components/Experience/History/Vertical.tsx
  src/lib/components/VisitorComment/CommentInput.tsx
  src/lib/components/VisitorComment/CommentList/Basic.tsx
  src/lib/components/VisitorComment/CommentList/Box.tsx
  src/lib/components/VisitorComment/CommentList/Vertical.tsx
  src/lib/components/VisitorComment/VisitorComment.tsx
  src/lib/components/VisitorCounter/BigSize.tsx
  src/lib/components/VisitorCounter/Default.tsx
  src/lib/components/VisitorCounter/Simple.tsx
Labels: enhancement

#177 [Feat] add props in TechStackList and ProgressBar, etc.
  package-lock.json
  package.json
  src/App.tsx
  src/lib/common/types/ComponentTypes/TechStack/ProgressBarType.ts
  src/lib/common/types/ComponentTypes/TechStack/TechStackListType.ts
  src/lib/common/types/ComponentTypes/TechStack/TechStackNameType.ts
  src/lib/common/types/ComponentTypes/TechStack/TechStackType.ts
  src/lib/components/ProgressBar/ProgressBar.tsx
  src/lib/components/TechStack/TechStacks/TechStackList.tsx
  src/lib/components/TechStack/TechStacks/TechStackName.tsx
  src/lib/components/VisitorComment/VisitorComment.tsx
Labels: enhancement

#179 feat(fix): fix sidebar component in mobile display #164
  src/lib/components/Header/SideContainer/SideBar.tsx
Labels: bug

#180 [Update] Update props names of VisitorCounter and Edit typedoc...
  package-lock.json
  package.json
  src/App.tsx
  src/lib/common/types/ComponentTypes/VisitorCounterType.ts
  src/lib/components/VisitorCounter/BigSize.tsx
  src/lib/components/VisitorCounter/Default.tsx
  src/lib/components/VisitorCounter/Simple.tsx
  src/lib/components/VisitorCounter/VisitorCounter.tsx
Labels: Refactor, enhancement

#178 docs: modify README.md about new props (#164)
  README.md
Labels: Chore

#181 docs: update documents regarding upgaraded functions
  README.md
  src/lib/common/types/ComponentTypes/TechStack/TechStackListType.ts
  src/lib/components/TechStack/TechStacks/TechStackList.tsx
Labels: Chore

#183 feat: change VisitorComment, VisitorCounter components to improve #164
  src/App.tsx
  src/lib/components/VisitorComment/VisitorComment.tsx
  src/lib/components/VisitorCounter/Default.tsx
Labels: Chore

#186 [Deploy] renewal new version
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/lib/common/types/ComponentTypes/ChannelType.ts
  src/lib/common/types/ComponentTypes/Contact/AboutMeInfoType.ts
  src/lib/common/types/ComponentTypes/Contact/ContactType.ts
  src/lib/common/types/ComponentTypes/ExperienceType.ts
  src/lib/common/types/ComponentTypes/Header/HeaderType.ts
  src/lib/common/types/ComponentTypes/ImageType.ts
  src/lib/common/types/ComponentTypes/IntroType.ts
  src/lib/common/types/ComponentTypes/ItemType.ts
  src/lib/common/types/ComponentTypes/SkillType.ts
  src/lib/common/types/ComponentTypes/TechStack/ProgressBarType.ts
  src/lib/common/types/ComponentTypes/TechStack/TechStackListType.ts
  src/lib/common/types/ComponentTypes/TechStack/TechStackNameType.ts
  src/lib/common/types/ComponentTypes/TechStack/TechStackType.ts
  src/lib/common/types/ComponentTypes/VisitorCommentType.ts
  src/lib/common/types/ComponentTypes/VisitorCounterType.ts
  src/lib/components/Carousel/hooks.tsx
  src/lib/components/Channels/Channels.tsx
  src/lib/components/Contact/AboutMe.tsx
  src/lib/components/Contact/Contact.tsx
  src/lib/components/Contact/ContactForm.tsx
  src/lib/components/Experience/Experience.tsx
  src/lib/components/Experience/History/Basic.tsx
  src/lib/components/Experience/History/Box.tsx
  src/lib/components/Experience/History/Vertical.tsx
  src/lib/components/Gallery/Gallery.tsx
  src/lib/components/Header/SideContainer/SideBar.tsx
  src/lib/components/Image/Image.tsx
  src/lib/components/Intro/Intro.tsx
  src/lib/components/Intro/IntroForm.tsx
  src/lib/components/Intro/IntroTitle.tsx
  src/lib/components/Item/Item.tsx
  src/lib/components/ProgressBar/ProgressBar.tsx
  src/lib/components/Skill/Skill.tsx
  src/lib/components/TechStack/TechStacks/TechStackList.tsx
  src/lib/components/TechStack/TechStacks/TechStackName.tsx
  src/lib/components/VisitorComment/CommentInput.tsx
  src/lib/components/VisitorComment/CommentList/Basic.tsx
  src/lib/components/VisitorComment/CommentList/Box.tsx
  src/lib/components/VisitorComment/CommentList/Vertical.tsx
  src/lib/components/VisitorComment/VisitorComment.tsx
  src/lib/components/VisitorCounter/BigSize.tsx
  src/lib/components/VisitorCounter/Default.tsx
  src/lib/components/VisitorCounter/Simple.tsx
  src/lib/components/VisitorCounter/VisitorCounter.tsx
Labels: bug, Refactor, enhancement, Chore, deploy, build

#189 fix: fix eslint warning (#187)
  src/App.tsx
  src/lib/common/utils/index.ts
  src/lib/common/utils/uuidv4.ts
  src/lib/components/Carousel/Carousel.tsx
  src/lib/components/Channels/Channels.tsx
  src/lib/components/Contact/AboutMe.tsx
  src/lib/components/Experience/Experience.tsx
  src/lib/components/Header/SideContainer/SideBarItems.tsx
  src/lib/components/Item/Item.tsx
  src/lib/components/TechStack/TechStackInput.tsx
  src/lib/components/TechStack/TechStacks/TechStackList.tsx
  src/lib/components/VisitorComment/VisitorComment.tsx
Labels: bug

#190 fix: ESLint error: Parsing error
  .eslintrc.js
Labels: bug

#192 fix: statement not part of import statement
  .eslintrc.js
Labels: bug

#193 fix: specify type to sideBarItems state (#187)
  src/lib/components/Header/SideContainer.tsx
Labels: bug

#196 [Deploy] update version v2.1.1
  src/lib/components/ProgressBar/index.ts
  src/lib/components/TechStack/TechStacks/TechStack.tsx
  src/lib/components/VisitorComment/VisitorComment.tsx
  src/lib/index.ts
Labels: deploy

#197 docs: correcting typos on README.md
  README.md
Labels: docs

#200 [Docs] Update README.md of v2.1.1
  README.md
Labels: docs

#202 Add .nvmrc build file so that NVM can manage dev-portfolio node version
  .nvmrc
Labels: enhancement

#209 Fix enable to line break in Item component
  src/lib/components/Item/Item.tsx
Labels: bug

#211 fix: remove onMouseDown and onMouseUp event (#210)
  src/lib/components/Carousel/hooks.tsx
Labels: bug

#221 [Fix] make textRising works (#216)
  src/lib/components/Item/Item.tsx
Labels: bug, enhancement

#222 feat: Add image loading component (#217)
  src/lib/components/Image/Image.tsx
  src/lib/components/Item/Item.tsx
  src/lib/components/Lazy/Image.tsx
  src/lib/components/Lazy/index.ts
  src/lib/components/Loader/Spinner.tsx
  src/lib/components/Loader/index.ts
Labels: enhancement

#224 chore: change arrowPosition into arrowLocation (#219)
  README.md
  src/lib/common/types/ComponentTypes/CarouselType.ts
  src/lib/components/Carousel/Carousel.tsx
Labels: chore
