Repository modern-agile-team/dev-portfolio, pull requests merged in 2022-09, with the labels that each got.

#107 [Feat] create the VisitorComment components (#90)
  app/src/App.tsx
  app/src/lib/common/types/ComponentTypes/VisitorCommentType.ts
  app/src/lib/components/VisitorComment/CommentInput.tsx
  app/src/lib/components/VisitorComment/CommentList/Basic.tsx
  app/src/lib/components/VisitorComment/CommentList/Box.tsx
  app/src/lib/components/VisitorComment/CommentList/Vertical.tsx
  app/src/lib/components/VisitorComment/CommentList/index.tsx
  app/src/lib/components/VisitorComment/VisitorComment.tsx
  app/src/lib/index.ts
Labels: enhancement

#108 [Feat] create VisitorCounter components (#91)
  app/package-lock.json
  app/src/App.tsx
  app/src/lib/common/types/ComponentTypes/VisitorCounterType.ts
  app/src/lib/components/VisitorCounter/BigSize.tsx
  app/src/lib/components/VisitorCounter/Default.tsx
  app/src/lib/components/VisitorCounter/Simple.tsx
  app/src/lib/components/VisitorCounter/VisitorCounter.tsx
  app/src/lib/index.ts
Labels: enhancement

#110 [Docs] add typedoc of carousel (#109)
  app/src/lib/common/types/ComponentTypes/CarouselType.ts
  app/src/lib/components/Carousel/Carousel.tsx
Labels: enhancement

#118 [Update] refine the default props of components
  app/package.json
  app/src/App.tsx
  app/src/lib/common/types/ComponentTypes/ExperienceType.ts
  app/src/lib/common/types/ComponentTypes/Header/HeaderType.ts
  app/src/lib/components/Experience/Experience.tsx
  app/src/lib/components/Header/Header.tsx
  app/src/lib/components/Intro/Intro.tsx
  app/src/lib/components/VisitorComment/VisitorComment.tsx
Labels: Chore

#121 [Docs] add typedocs (#111)
  app/src/lib/common/types/ComponentTypes/VisitorCommentType.ts
  app/src/lib/common/types/ComponentTypes/VisitorCounterType.ts
  app/src/lib/components/Channels/Channels.tsx
  app/src/lib/components/VisitorComment/VisitorComment.tsx
  app/src/lib/components/VisitorCounter/VisitorCounter.tsx
Labels: help wanted

#123 Feature/pwr/#122
  app/package.json
  app/src/lib/common/theme.ts
  app/src/lib/common/types/main.ts
  app/src/lib/components/TechStack/TechStackInput.tsx
Labels: enhancement, Chore

#124 [Chore] detailed work for a high-quality finished product (#120)
  app/src/lib/components/Contact/Contact.tsx
  app/src/lib/components/Header/HeaderLogo.tsx
  app/src/lib/components/Header/SideContainer/SideBarItems.tsx
  app/src/lib/components/Item/Item.tsx
  app/src/lib/components/TechStack/TechStackInput.tsx
  app/src/lib/components/TechStack/TechStacks/TechStackList.tsx
  app/src/lib/components/VisitorComment/CommentInput.tsx
  app/src/lib/components/VisitorComment/CommentList/Basic.tsx
  app/src/lib/components/VisitorComment/CommentList/Box.tsx
  app/src/lib/components/VisitorComment/CommentList/Vertical.tsx
  app/src/lib/components/VisitorComment/VisitorComment.tsx
  app/src/lib/components/VisitorCounter/Default.tsx
Labels: Chore

#139 [Chore] remove useless static files in public folder #138
  public/logo_test.png
  public/manifest.json
Labels: Chore

#140 [Deploy] merge version v1.1.0
  public/logo_test.png
  public/manifest.json
  src/lib/common/types/ComponentTypes/VisitorCommentType.ts
  src/lib/components/Item/Item.tsx
  src/lib/components/VisitorComment/CommentInput.tsx
  src/lib/components/VisitorComment/CommentList/Basic.tsx
  src/lib/components/VisitorComment/CommentList/Box.tsx
  src/lib/components/VisitorComment/CommentList/Vertical.tsx
  src/lib/components/VisitorComment/VisitorComment.tsx
Labels: bug, Chore

#141 [Docs] add Contribute.md
  Contribute.md
Labels: help wanted

#144 [Update] reinforce carousel component (#142)
  src/App.tsx
  src/lib/common/hooks/index.ts
  src/lib/common/hooks/useInterval.tsx
  src/lib/components/Carousel/Carousel.tsx
  src/lib/components/Carousel/hooks.tsx
  src/lib/components/Carousel/style.tsx
Labels: enhancement

#146 [feature/pwr/#145] Upgrade UI of sidebar
  package-lock.json
  src/App.tsx
  src/lib/common/types/ComponentTypes/Header/SideBar/SideBarIconType.ts
  src/lib/common/types/ComponentTypes/Header/SideBar/SideBarItemsType.ts
  src/lib/common/types/ComponentTypes/Header/SideBar/SideBarType.ts
  src/lib/components/Channels/Channels.tsx
  src/lib/components/Header/Header.tsx
  src/lib/components/Header/SideContainer.tsx
  src/lib/components/Header/SideContainer/SideBar.tsx
  src/lib/components/Header/SideContainer/SideBarIcon.tsx
  src/lib/components/Header/SideContainer/SideBarItems.tsx
Labels: enhancement

#148 [Deploy] update version to v1.2.0
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/lib/common/hooks/index.ts
  src/lib/common/hooks/useInterval.tsx
  src/lib/common/types/ComponentTypes/Header/SideBar/SideBarIconType.ts
  src/lib/common/types/ComponentTypes/Header/SideBar/SideBarItemsType.ts
  src/lib/common/types/ComponentTypes/Header/SideBar/SideBarType.ts
  src/lib/components/Carousel/Carousel.tsx
  src/lib/components/Carousel/hooks.tsx
  src/lib/components/Carousel/style.tsx
  src/lib/components/Channels/Channels.tsx
  src/lib/components/Header/Header.tsx
  src/lib/components/Header/SideContainer.tsx
  src/lib/components/Header/SideContainer/SideBar.tsx
  src/lib/components/Header/SideContainer/SideBarIcon.tsx
  src/lib/components/Header/SideContainer/SideBarItems.tsx
Labels: enhancement, help wanted, Chore

#150 [Deploy] update version to v1.2.1
  README.md
  package-lock.json
  package.json
Labels: Chore

#151 [Refactor] remove optional props
  README.md
  src/lib/common/types/ComponentTypes/Contact/ContactType.ts
  src/lib/common/types/ComponentTypes/ExperienceType.ts
  src/lib/common/types/ComponentTypes/IntroType.ts
  src/lib/components/Contact/Contact.tsx
  src/lib/components/Contact/ContactForm.tsx
  src/lib/components/Experience/Experience.tsx
  src/lib/components/Intro/Intro.tsx
Labels: Refactor
